title: MainWP Developer Documentation
description: Comprehensive documentation for MainWP extension and integration development
baseurl: "/mainwp.dev" # Subpath for GitHub Pages project site
url: "https://mainwp.github.io" # Production domain for GitHub Pages

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme settings
layouts_dir: dox-theme/_layouts
includes_dir: dox-theme/_includes
sass:
  sass_dir: dox-theme/_sass
  style: compressed
  load_paths:
    - _sass
    - dox-theme/_sass

# Collections
collections:
  documentation:
    output: true
  guides:
    output: true
  hooks:
    output: true
  api:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: documentation-single

# Exclude from processing
exclude:
  - README.md
  - CHANGELOG.md
  - LICENSE             # Add LICENSE
  - .git
  - .gitignore
  - .github             # Add .github
  - .bundle             # Add .bundle
  - hooks-generator
  - memory-bank
  - .clineignore
  - .clinerules         # Corrected from .clinerules.md
  - vendor
  - Gemfile
  - Gemfile.lock
  - composer.json       # Add composer files
  - composer.lock       # Add composer files
  - deploy-test         # Add deploy-test
  - developer-changelog.md # Add developer-changelog.md
  - generate-docs.sh    # Add generate-docs.sh
  - mainwp-hooks-old    # Add mainwp-hooks-old
  - mainwp-hooks-temp   # Add mainwp-hooks-temp
  - phpdoc              # Add phpdoc (assuming temporary/source)
  - preview-code-blocks.html # Add preview-code-blocks.html
  # - source-code       # DO NOT EXCLUDE - This is phpDocumentor output
  - sources             # Add sources
  - test-code.html      # Add test files
  - test-deploy.sh      # Add test files
  - test-header.html    # Add test files
  - test-navigation-style.css # Add test files
  - test-navigation.html # Add test files
  - test-page-nav.html  # Add test files
